-- MySQL Script generated by MySQL Workbench
-- Fri Sep  9 11:14:48 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`perfil`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`perfil` ;

CREATE TABLE IF NOT EXISTS `mydb`.`perfil` (
  `idperfil` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`idperfil`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`usuario` ;

CREATE TABLE IF NOT EXISTS `mydb`.`usuario` (
  `idusuario` INT NOT NULL AUTO_INCREMENT,
  `perfil_idperfil` INT NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `senha` VARCHAR(12) NOT NULL,
  `status` SMALLINT(1) NOT NULL,
  PRIMARY KEY (`idusuario`),
  INDEX `fk_usuario_perfil_idx` (`perfil_idperfil` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_perfil`
    FOREIGN KEY (`perfil_idperfil`)
    REFERENCES `mydb`.`perfil` (`idperfil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`fornecedor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`fornecedor` ;

CREATE TABLE IF NOT EXISTS `mydb`.`fornecedor` (
  `idfornecedor` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) NOT NULL,
  `razao_social` VARCHAR(150) NOT NULL,
  `documento` VARCHAR(50) NOT NULL,
  `logradouro` VARCHAR(100) NOT NULL,
  `complemento` VARCHAR(20) NULL,
  `bairro` VARCHAR(50) NOT NULL,
  `cidade` VARCHAR(50) NOT NULL,
  `cep` VARCHAR(9) NOT NULL,
  `contato` VARCHAR(50) NOT NULL,
  `telefone` VARCHAR(20) NULL,
  `email` VARCHAR(50) NULL,
  `status` SMALLINT(1) NOT NULL,
  PRIMARY KEY (`idfornecedor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`unidade_medidas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`unidade_medidas` ;

CREATE TABLE IF NOT EXISTS `mydb`.`unidade_medidas` (
  `idunidade_medidas` INT NOT NULL AUTO_INCREMENT,
  `codigo` VARCHAR(5) NOT NULL,
  `descricao` VARCHAR(50) NOT NULL,
  `status` SMALLINT(1) NOT NULL,
  PRIMARY KEY (`idunidade_medidas`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`materia_prima`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`materia_prima` ;

CREATE TABLE IF NOT EXISTS `mydb`.`materia_prima` (
  `idmateria_prima` INT NOT NULL AUTO_INCREMENT,
  `idfornecedor` INT NOT NULL,
  `idunidade_medidas` INT NOT NULL,
  `nome` VARCHAR(50) NOT NULL,
  `descricao` VARCHAR(50) NOT NULL,
  `cor` VARCHAR(45) NULL,
  `status` SMALLINT(1) NOT NULL,
  PRIMARY KEY (`idmateria_prima`),
  INDEX `fk_materia_prima_fornecedor1_idx` (`idfornecedor` ASC) VISIBLE,
  INDEX `fk_materia_prima_unidade_medidas1_idx` (`idunidade_medidas` ASC) VISIBLE,
  CONSTRAINT `fk_materia_prima_fornecedor1`
    FOREIGN KEY (`idfornecedor`)
    REFERENCES `mydb`.`fornecedor` (`idfornecedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_materia_prima_unidade_medidas1`
    FOREIGN KEY (`idunidade_medidas`)
    REFERENCES `mydb`.`unidade_medidas` (`idunidade_medidas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`estoque`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`estoque` ;

CREATE TABLE IF NOT EXISTS `mydb`.`estoque` (
  `idestoque` INT NOT NULL AUTO_INCREMENT,
  `idmateria_prima` INT NOT NULL,
  `quantidade` DOUBLE NOT NULL,
  `status` SMALLINT(1) NOT NULL,
  PRIMARY KEY (`idestoque`),
  INDEX `fk_estoque_materia_prima1_idx` (`idmateria_prima` ASC) VISIBLE,
  CONSTRAINT `fk_estoque_materia_prima1`
    FOREIGN KEY (`idmateria_prima`)
    REFERENCES `mydb`.`materia_prima` (`idmateria_prima`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`cliente` ;

CREATE TABLE IF NOT EXISTS `mydb`.`cliente` (
  `idcliente` INT NOT NULL AUTO_INCREMENT,
  `documento` VARCHAR(20) NOT NULL,
  `nome` VARCHAR(50) NOT NULL,
  `logradouro` VARCHAR(100) NOT NULL,
  `complemento` VARCHAR(20) NULL,
  `bairro` VARCHAR(50) NOT NULL,
  `cidade` VARCHAR(50) NOT NULL,
  `estado` VARCHAR(2) NOT NULL,
  `cep` VARCHAR(9) NOT NULL,
  `contato` VARCHAR(50) NULL,
  `telefone` VARCHAR(20) NULL,
  `email` VARCHAR(50) NULL,
  `status` SMALLINT(1) NOT NULL,
  `clientecol` VARCHAR(45) NULL,
  PRIMARY KEY (`idcliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`produto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`produto` ;

CREATE TABLE IF NOT EXISTS `mydb`.`produto` (
  `idproduto` INT NOT NULL AUTO_INCREMENT,
  `codigo` VARCHAR(10) NOT NULL,
  `nome` VARCHAR(50) NOT NULL,
  `valor` DOUBLE NOT NULL,
  `status` SMALLINT(1) NOT NULL,
  PRIMARY KEY (`idproduto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`orcamento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`orcamento` ;

CREATE TABLE IF NOT EXISTS `mydb`.`orcamento` (
  `idorcamento` INT NOT NULL AUTO_INCREMENT,
  `idproduto` INT NOT NULL,
  `data` DATETIME NOT NULL,
  `subtotal` DOUBLE NOT NULL,
  `desconto` DOUBLE NOT NULL,
  `total` DOUBLE NOT NULL,
  `status` SMALLINT(1) NOT NULL,
  PRIMARY KEY (`idorcamento`),
  INDEX `fk_orcamento_produto1_idx` (`idproduto` ASC) VISIBLE,
  CONSTRAINT `fk_orcamento_produto1`
    FOREIGN KEY (`idproduto`)
    REFERENCES `mydb`.`produto` (`idproduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`itens_orcamento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`itens_orcamento` ;

CREATE TABLE IF NOT EXISTS `mydb`.`itens_orcamento` (
  `iditens_orcamento` INT NOT NULL AUTO_INCREMENT,
  `idorcamento` INT NOT NULL,
  `idcliente` INT NOT NULL,
  `idproduto` INT NOT NULL,
  `valor` DOUBLE NOT NULL,
  `desconto` DOUBLE NOT NULL,
  `total` DOUBLE NOT NULL,
  PRIMARY KEY (`iditens_orcamento`),
  INDEX `fk_itens_orcamento_cliente1_idx` (`idcliente` ASC) VISIBLE,
  INDEX `fk_itens_orcamento_orcamento1_idx` (`idorcamento` ASC) VISIBLE,
  INDEX `fk_itens_orcamento_produto1_idx` (`idproduto` ASC) VISIBLE,
  CONSTRAINT `fk_itens_orcamento_cliente1`
    FOREIGN KEY (`idcliente`)
    REFERENCES `mydb`.`cliente` (`idcliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_itens_orcamento_orcamento1`
    FOREIGN KEY (`idorcamento`)
    REFERENCES `mydb`.`orcamento` (`idorcamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_itens_orcamento_produto1`
    FOREIGN KEY (`idproduto`)
    REFERENCES `mydb`.`produto` (`idproduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`itens_orcamento_materia_prima`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`itens_orcamento_materia_prima` ;

CREATE TABLE IF NOT EXISTS `mydb`.`itens_orcamento_materia_prima` (
  `iditens_orcamento_materia_prima` INT NOT NULL AUTO_INCREMENT,
  `idmateria_prima` INT NOT NULL,
  `iditens_orcamento` INT NOT NULL,
  `quantidade` DOUBLE NOT NULL,
  PRIMARY KEY (`iditens_orcamento_materia_prima`),
  INDEX `fk_itens_orcamento_materia_prima_materia_prima1_idx` (`idmateria_prima` ASC) VISIBLE,
  INDEX `fk_itens_orcamento_materia_prima_itens_orcamento1_idx` (`iditens_orcamento` ASC) VISIBLE,
  CONSTRAINT `fk_itens_orcamento_materia_prima_materia_prima1`
    FOREIGN KEY (`idmateria_prima`)
    REFERENCES `mydb`.`materia_prima` (`idmateria_prima`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_itens_orcamento_materia_prima_itens_orcamento1`
    FOREIGN KEY (`iditens_orcamento`)
    REFERENCES `mydb`.`itens_orcamento` (`iditens_orcamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`produto_materia_prima`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`produto_materia_prima` ;

CREATE TABLE IF NOT EXISTS `mydb`.`produto_materia_prima` (
  `idproduto_materia_prima` INT NOT NULL AUTO_INCREMENT,
  `unidaidunidade_medidas` INT NOT NULL,
  `idproduto` INT NOT NULL,
  `quantidade` DOUBLE NOT NULL,
  PRIMARY KEY (`idproduto_materia_prima`),
  INDEX `fk_produto_materia_prima_unidade_medidas1_idx` (`unidaidunidade_medidas` ASC) VISIBLE,
  INDEX `fk_produto_materia_prima_produto1_idx` (`idproduto` ASC) VISIBLE,
  CONSTRAINT `fk_produto_materia_prima_unidade_medidas1`
    FOREIGN KEY (`unidaidunidade_medidas`)
    REFERENCES `mydb`.`unidade_medidas` (`idunidade_medidas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_produto_materia_prima_produto1`
    FOREIGN KEY (`idproduto`)
    REFERENCES `mydb`.`produto` (`idproduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
